package redactdesk;

import java.nio.file.Path;

public final class StoreTest {
    public static void main(String[] args) throws Exception { int passed = 0; passed += run("loads and sorts documents", StoreTest::loadsAndSortsDocuments); passed += run("filters approved documents", StoreTest::filtersApproved); passed += run("adds manual redaction and increments revisions", StoreTest::addsManualRedaction); passed += run("rejects stale manual write without mutation", StoreTest::rejectsStaleWrite); passed += run("rejects overlapping manual redaction", StoreTest::rejectsOverlap); passed += run("approved document remains locked", StoreTest::approvedLocked); passed += run("suggestion fixture loads", StoreTest::suggestionFixtureLoads); System.out.println("StoreTest: " + passed + "/7 passed"); }
    private static Store fresh() throws Exception { return Store.load(Path.of("fixtures")); }
    private static void loadsAndSortsDocuments() throws Exception { var result = fresh().listDocuments("all"); TestSupport.equal(3, result.documents().size(), "document count"); TestSupport.equal("doc-300", result.documents().get(0).id(), "title ordering"); TestSupport.equal(1L, result.datasetRevision(), "initial dataset revision"); }
    private static void filtersApproved() throws Exception { var result = fresh().listDocuments("approved"); TestSupport.equal(1, result.documents().size(), "approved count"); TestSupport.equal("doc-300", result.documents().get(0).id(), "approved document"); }
    private static void addsManualRedaction() throws Exception { Store store = fresh(); var before = store.getDocument("doc-100"); var result = store.addManualRedaction("doc-100", 1, 8, 18, "personal", " Name ", before.document().revision()); TestSupport.equal(before.document().revision() + 1, result.document().revision(), "document revision"); TestSupport.equal(before.datasetRevision() + 1, result.datasetRevision(), "dataset revision"); TestSupport.equal("Name", result.redaction().note(), "note trimming"); TestSupport.equal(2, result.document().redactions().size(), "redaction count"); }
    private static void rejectsStaleWrite() throws Exception { Store store = fresh(); int revision = store.getDocument("doc-100").document().revision(); store.addManualRedaction("doc-100", 1, 8, 18, "personal", "Name", revision); var error = TestSupport.expectApi("stale_revision", () -> store.addManualRedaction("doc-100", 1, 75, 87, "credentials", "Password", revision)); TestSupport.equal(409, error.status, "stale status"); TestSupport.equal(2, store.getDocument("doc-100").document().redactions().size(), "no stale mutation"); }
    private static void rejectsOverlap() throws Exception { Store store = fresh(); int revision = store.getDocument("doc-100").document().revision(); TestSupport.expectApi("range_overlap", () -> store.addManualRedaction("doc-100", 1, 30, 40, "personal", "Overlap", revision)); TestSupport.equal(revision, store.getDocument("doc-100").document().revision(), "revision unchanged"); }
    private static void approvedLocked() throws Exception { Store store = fresh(); int revision = store.getDocument("doc-300").document().revision(); TestSupport.expectApi("document_locked", () -> store.addManualRedaction("doc-300", 1, 0, 8, "personal", "Nope", revision)); }
    private static void suggestionFixtureLoads() throws Exception { Store store = fresh(); TestSupport.isTrue(store.getSuggestions("doc-100").size() >= 8, "expected representative suggestions"); TestSupport.equal(1, store.getSuggestions("doc-300").size(), "approved fixture suggestion"); }
    private static int run(String name, Checked test) throws Exception { try { test.run(); System.out.println("PASS " + name); return 1; } catch (Throwable t) { System.err.println("FAIL " + name + ": " + t); throw t; } }
    @FunctionalInterface private interface Checked { void run() throws Exception; }
}
