import { api } from "./api.js";
import { state, selectedOrderSummary } from "./store.js";
const $ = (s) => document.querySelector(s);
async function loadOrders() { const data = await api.orders(); state.orders = data.orders; state.inventoryRevision = data.inventory_revision; if (!state.selectedOrderId && state.orders.length) state.selectedOrderId = state.orders[0].id; if (state.selectedOrderId) await loadOrder(state.selectedOrderId); }
async function loadOrder(id) { const data = await api.order(id); state.selectedOrderId=id; state.selectedOrder=data.order; state.inventoryRevision=data.inventory_revision; }
async function loadInventory() { const data = await api.inventory(state.skuFilter); state.inventory=data.items; state.inventoryRevision=data.revision; }
async function refresh() { state.loading=true; state.error=null; render(); try { await Promise.all([loadOrders(),loadInventory()]); } catch(e){state.error=e.message;} finally {state.loading=false;render();} }
function render() { $("#status").textContent = state.error || (state.loading ? "Loading…" : `Inventory revision ${state.inventoryRevision ?? "—"}`); $("#orders").innerHTML = state.orders.map(o => `<button class="order ${o.id===state.selectedOrderId?'selected':''}" data-id="${o.id}"><strong>${o.id}</strong><span>${o.customer}</span><small>${o.status}</small></button>`).join(""); $("#order-detail").innerHTML = state.selectedOrder ? `<h2>${selectedOrderSummary()}</h2><ul>${state.selectedOrder.lines.map(l=>`<li>${l.sku} × ${l.qty}</li>`).join("")}</ul>` : ""; $("#inventory-body").innerHTML = state.inventory.map(i=>`<tr><td>${i.sku}</td><td>${i.warehouse_id}</td><td>${i.on_hand}</td><td>${i.reserved}</td><td>${i.available}</td></tr>`).join(""); }
document.addEventListener("click", async (e)=>{ const b=e.target.closest("[data-id]"); if(!b)return; try{await loadOrder(b.dataset.id);render();}catch(err){state.error=err.message;render();} });
$("#filter").addEventListener("input", async (e)=>{ state.skuFilter=e.target.value; try{await loadInventory();render();}catch(err){state.error=err.message;render();} });
$("#adjust-form").addEventListener("submit", async (e)=>{ e.preventDefault(); const fd=new FormData(e.target); state.error=null; try { await api.adjust({warehouse_id:fd.get("warehouse_id"),sku:fd.get("sku"),delta:Number(fd.get("delta")),expected_revision:state.inventoryRevision,reason:fd.get("reason")}); e.target.reset(); await Promise.all([loadInventory(),loadOrders()]); } catch(err){ state.error=err.message; if(err.body?.revision) state.inventoryRevision=err.body.revision; } render(); });
refresh();
